language: go

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x
  - tip

# Only clone the most recent commit.
git:
  depth: 1

# Specify which operating systems to test on
os:
  - windows
  - linux
  - osx

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Build marix for customizing different jobs
matrix:
  allow_failures:
    - os: windows

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic  # Run all go tests

# run after tests successfully finish
after_success:
  - bash <(curl -s https://codecov.io/bash)